In [2]:
import numpy as np
import pandas as pd
import difflib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [3]:
# loading the data from the csv file 
movie_data = pd.read_csv('movies.csv')

# printing the first 5 rows of the dataset
movie_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

## Get the Number of rows and columns in the dataset

In [4]:
movie_data.shape

(4803, 24)

In [5]:
# Selecting the relevant features for recommendation

selected_features = ['genres', 'keywords', 'original_title', 'overview', 'tagline', 'title', 'cast', 'director']

print(selected_features)

['genres', 'keywords', 'original_title', 'overview', 'tagline', 'title', 'cast', 'director']


In [6]:
# replacing the null values with a null string

for feature in selected_features:
    movie_data[feature] = movie_data[feature].fillna('')

In [7]:
# combining the selected features 

combined_features = movie_data['genres'] + ' ' + movie_data['keywords'] + ' ' + movie_data['original_title'] + ' ' + movie_data['overview'] + ' ' + movie_data['tagline'] + ' ' + movie_data['title'] + ' ' + movie_data['cast'] + ' ' + movie_data['director']

print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  Newlyweds A newlywed couple's ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      Shanghai Calling When ambitious New York att...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


Converting the text data to feature vectors


In [8]:
vectorizer = TfidfVectorizer()

features_vectors = vectorizer.fit_transform(combined_features)

In [9]:
print(features_vectors)

  (0, 576)	0.05552287249490444
  (0, 721)	0.06361667418861082
  (0, 10053)	0.07921109292531174
  (0, 24720)	0.07389117037591678
  (0, 10333)	0.07397626570741078
  (0, 6822)	0.13944649029207198
  (0, 5464)	0.14412534728090148
  (0, 11141)	0.10293144610710211
  (0, 26211)	0.2249184223444861
  (0, 30414)	0.07997028866714566
  (0, 5784)	0.16116678982694885
  (0, 26020)	0.12400247973187499
  (0, 2141)	0.3772968432669652
  (0, 13904)	0.03370327087232612
  (0, 27972)	0.0757439774177829
  (0, 241)	0.1834455854038367
  (0, 4929)	0.1160534030595115
  (0, 20746)	0.17919455867442288
  (0, 17554)	0.13273886777572982
  (0, 14473)	0.03871367606514675
  (0, 8076)	0.1672840999284348
  (0, 28275)	0.02873959179822235
  (0, 18823)	0.13382353287729085
  (0, 20677)	0.34497387231616145
  (0, 20161)	0.045290151056417934
  :	:
  (4802, 22067)	0.08065544619548977
  (4802, 9456)	0.07035435415169015
  (4802, 24851)	0.07357664702665985
  (4802, 6340)	0.09681765169562287
  (4802, 14779)	0.08873654894555631
  (4802,

Cosine Similarity Algorithm

In [10]:
# Getting the similarity scores between the features using cosine similarity

similarity = cosine_similarity(features_vectors)

print(similarity)

print("rows and column: ", similarity.shape)

[[1.         0.05176078 0.02708462 ... 0.020484   0.02434631 0.00590704]
 [0.05176078 1.         0.03598704 ... 0.0511643  0.03780307 0.01469859]
 [0.02708462 0.03598704 1.         ... 0.01877076 0.03625338 0.01071917]
 ...
 [0.020484   0.0511643  0.01877076 ... 1.         0.0243797  0.03974862]
 [0.02434631 0.03780307 0.03625338 ... 0.0243797  1.         0.02560517]
 [0.00590704 0.01469859 0.01071917 ... 0.03974862 0.02560517 1.        ]]
rows and column:  (4803, 4803)


In [11]:
# Getting the movie name from the user

movie_name = input('Enter Your Favorite Movie Name: ')

print(movie_name)

Batman


In [12]:
# Creating a list with all the movie names given in the input

list_of_all_titles = movie_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [13]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

print(find_close_match)

['Batman', 'Batman', 'Catwoman']


In [14]:
close_match = find_close_match[0]

print(close_match)

Batman


In [15]:
# Finding the index with title

index_of_movie = movie_data[movie_data.title == close_match]['index'].values[0]
print(index_of_movie)

1359


In [16]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_movie]))

print(similarity_score)

[(0, 0.026888064459182508), (1, 0.04991178659531042), (2, 0.021073541253854293), (3, 0.31776638190075956), (4, 0.030992133854809867), (5, 0.05372946836698987), (6, 0.023031319181390637), (7, 0.026117037451518398), (8, 0.05820032079891537), (9, 0.21156556568665016), (10, 0.06549402285358003), (11, 0.027463738256379627), (12, 0.042950438728500656), (13, 0.020972187546200585), (14, 0.07989544974055163), (15, 0.03990742092048321), (16, 0.04447020874662443), (17, 0.0529615874287313), (18, 0.048548350010218476), (19, 0.04905785116833436), (20, 0.04941488027071955), (21, 0.042387958619911896), (22, 0.02927207771172598), (23, 0.018733832207315195), (24, 0.028826825850718805), (25, 0.030603798323458373), (26, 0.03603365710807758), (27, 0.03464992586474959), (28, 0.007468984071303558), (29, 0.024206012599797377), (30, 0.09730231611506868), (31, 0.020758455543080593), (32, 0.047327009681037195), (33, 0.015382758291159357), (34, 0.006342704252881472), (35, 0.03983020025676318), (36, 0.057495956356

In [17]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

print(sorted_similar_movies)


[(1359, 1.0), (428, 0.4046974131003657), (119, 0.3592895130767284), (3854, 0.33564878801550097), (210, 0.32041335944789034), (3, 0.31776638190075956), (65, 0.3108798005064792), (299, 0.2840532506065042), (9, 0.21156556568665016), (4267, 0.17246192036937633), (2291, 0.12321706667830266), (2029, 0.10443710155053171), (2079, 0.10112536297299154), (1390, 0.10049339907315358), (3404, 0.09917451141183238), (30, 0.09730231611506868), (72, 0.09534732213069368), (1247, 0.09469814901942371), (1469, 0.09252967955408434), (1001, 0.09048632700243285), (1512, 0.08991721066817573), (1461, 0.08708003007958717), (3297, 0.08510296607477934), (813, 0.08491498925073808), (2381, 0.08221107710935975), (1188, 0.08211948855992604), (3600, 0.08079086581245813), (4759, 0.08066723405719076), (14, 0.07989544974055163), (753, 0.07980540795767666), (1110, 0.07936338370507838), (2237, 0.07853681720538984), (41, 0.07852064493796225), (3438, 0.07847515120912006), (1368, 0.07785682621948635), (1017, 0.07772461578220305

In [18]:
# print the name of similar movies based on the index

print('Movies suggested for you: \n' )

for i in sorted_similar_movies[1:21]:
    print(movie_data['title'].iloc[i[0]])
    print('{:.2f}%'.format((i[1] * 100)) ) 
    print('---')
    print(' ')

    print(movie_data.iloc[i[0]])
    print('---')
    print(' ')

    # If you want to see the cast and director of each movie, uncomment the below line
    # print('Cast:', movie_data['cast'].iloc[i[0]].split(', '))
    # print('Director:', movie_data['director'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the genres of each movie, uncomment the below line
    # print('Genres:', movie_data['genres'].iloc[i[0]].split('|'))
    # print('---')
    # print(' ')

    # If you want to see the keywords of each movie, uncomment the below line
    # print('Keywords:', movie_data['keywords'].iloc[i[0]].split('|'))
    # print('---')
    # print(' ')

    # If you want to see the overview of each movie, uncomment the below line
    # print('Overview:', movie_data['overview'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the tagline of each movie, uncomment the below line
    # print('Tagline:', movie_data['tagline'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the original title of each movie, uncomment the below line
    # print('Original Title:', movie_data['original_title'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the release date of each movie, uncomment the below line
    # print('Release Date:', movie_data['release_date'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the popularity of each movie, uncomment the below line
    # print('Popularity:', movie_data['popularity'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the vote average of each movie, uncomment the below line
    # print('Vote Average:', movie_data['vote_average'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the vote count of each movie, uncomment the below line
    # print('Vote Count:', movie_data['vote_count'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the runtime of each movie, uncomment the below line
    # print('Runtime:', movie_data['runtime'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the budget of each movie, uncomment the below line
    # print('Budget:', movie_data['budget'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the revenue of each movie, uncomment the below line
    # print('Revenue:', movie_data['revenue'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the homepage of each movie, uncomment the below line
    # print('Homepage:', movie_data['homepage'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the status of each movie, uncomment the below line
    # print('Status:', movie_data['status'].iloc[i[0]])
    # print('---')
    # print(' ')

    # If you want to see the production companies of each movie, uncomment the below line
    # print('Production Companies:', movie_data['production_companies'].iloc[i[0]].split('|'))
    # print('---')
    # print(' ')

    # If you want to see the production countries of each movie, uncomment the below line
    # print('Production Countries:', movie_data['production_countries'].iloc[i[0]].split('|'))
    # print('---')
    # print(' ')

    # If you want to see the spoken languages of each movie, uncomment the below line
    # print('Spoken Languages:', movie_data['spoken_languages'].iloc[i[0]].split('|'))
    # print('---')
    # print(' ')

    

Movies suggested for you: 

Batman Returns
40.47%
---
 
index                                                                 428
budget                                                           80000000
genres                                                     Action Fantasy
homepage                                                              NaN
id                                                                    364
keywords                holiday corruption double life dc comics crime...
original_language                                                      en
original_title                                             Batman Returns
overview                Having defeated the Joker, Batman now faces th...
popularity                                                      59.113174
production_companies    [{"name": "PolyGram Filmed Entertainment", "id...
production_countries    [{"iso_3166_1": "GB", "name": "United Kingdom"...
release_date                                            

In [19]:
# Another Movie REcom System
movie_name = input('Enter Your Favorite Movie Name: ')

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_movie = movie_data[movie_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_movie]))

sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

print('Movies suggested for you: \n' )

for i in sorted_similar_movies[1:21]:
    print(movie_data['title'].iloc[i[0]])
    print('{:.2f}%'.format((i[1] * 100)) ) 
    print('---')
    print(' ')

    print(movie_data.iloc[i[0]])
    print('---')
    print(' ')

Movies suggested for you: 

Batman Returns
40.47%
---
 
index                                                                 428
budget                                                           80000000
genres                                                     Action Fantasy
homepage                                                              NaN
id                                                                    364
keywords                holiday corruption double life dc comics crime...
original_language                                                      en
original_title                                             Batman Returns
overview                Having defeated the Joker, Batman now faces th...
popularity                                                      59.113174
production_companies    [{"name": "PolyGram Filmed Entertainment", "id...
production_countries    [{"iso_3166_1": "GB", "name": "United Kingdom"...
release_date                                            